// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-eb7Kh60mbmfnnhYPNtOve3htPoYbW0Y',
    appId: '1:471522883420:web:821598c0e72bf0f6123399',
    messagingSenderId: '471522883420',
    projectId: 'admin-dashboard-2ea77',
    authDomain: 'admin-dashboard-2ea77.firebaseapp.com',
    storageBucket: 'admin-dashboard-2ea77.firebasestorage.app',
    measurementId: 'G-PN0E41QWKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgzj8MtnZrOjaTEyMoVoCVwdYW4sHUG_U',
    appId: '1:471522883420:android:f1969cd417b03d08123399',
    messagingSenderId: '471522883420',
    projectId: 'admin-dashboard-2ea77',
    storageBucket: 'admin-dashboard-2ea77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFAdQNHaKopyxixWTAhRUJRf5veqzudqk',
    appId: '1:471522883420:ios:5545a823ff78c311123399',
    messagingSenderId: '471522883420',
    projectId: 'admin-dashboard-2ea77',
    storageBucket: 'admin-dashboard-2ea77.firebasestorage.app',
    androidClientId: '471522883420-cuk10oefu2p8kgftn6d5moc3jjhcphkh.apps.googleusercontent.com',
    iosClientId: '471522883420-vfkdjomojtsc5oaci3f1460itnc8m0nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFromScratch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFAdQNHaKopyxixWTAhRUJRf5veqzudqk',
    appId: '1:471522883420:ios:5545a823ff78c311123399',
    messagingSenderId: '471522883420',
    projectId: 'admin-dashboard-2ea77',
    storageBucket: 'admin-dashboard-2ea77.firebasestorage.app',
    androidClientId: '471522883420-cuk10oefu2p8kgftn6d5moc3jjhcphkh.apps.googleusercontent.com',
    iosClientId: '471522883420-vfkdjomojtsc5oaci3f1460itnc8m0nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceFromScratch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-eb7Kh60mbmfnnhYPNtOve3htPoYbW0Y',
    appId: '1:471522883420:web:821598c0e72bf0f6123399',
    messagingSenderId: '471522883420',
    projectId: 'admin-dashboard-2ea77',
    authDomain: 'admin-dashboard-2ea77.firebaseapp.com',
    storageBucket: 'admin-dashboard-2ea77.firebasestorage.app',
    measurementId: 'G-PN0E41QWKW',
  );

}